export default [
  {
    name: "_2an",
    label: "__2AN",
    placeholder: "",
    tooltipText: "__2AN",
    tabName: "Identifier_tab",
    readOnly: true,
    type: "text",
    isMultilingual: false,
    validationType: "string",
    validations: [
      {
        type: "required",
        params: ["This field is required"],
      },
    ],
  },
  {
    name: "gtin",
    label: "_GTIN",
    placeholder: "",
    tooltipText: "_GTIN",
    tabName: "Identifier_tab",
    readOnly: true,
    type: "text",
    isMultilingual: false,
    validationType: "string",
    validations: [
      {
        type: "matches",
        params: [
          "^[0-9]{0}$|^[0-9]{8}$|^[0-9]{12}$|^[0-9]{14}$",
          "gtin should be 8 or 12 or 14 character & should be number.",
        ],
      },
    ],
  },
  {
    name: "businessIdentifiers_tab",
    label: "_Company",
    placeholder: "",
    tooltipText: "Business IDS",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "businessIdentifiers_tab",
    isMultilingual: false,
    options: [],
    validationType: "string",
    validations: [],
  },
  {
    name: "brandName",
    label: "_Brand Name",
    placeholder: "",
    tooltipText: "_Brand Name",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "text",
    isMultilingual: false,
    validationType: "string",
    validations: [
      {
        params: ["This field is required Brand Name"],
      },
    ],
  },
  {
    name: "profileActive",
    label: "Profile Active",
    placeholder: "",
    tooltipText: "Profile Active",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "switch",
    isMultilingual: false,
  },
  {
    name: "productName",
    label: "_Product Name",
    placeholder: "",
    tooltipText: "_Product Name",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "text",
    isMultilingual: true,
  },
  {
    name: "regulatedProductName",
    label: "_Regulated Product Name",
    placeholder: "",
    tooltipText: "_Regulated Product Name",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "text",
    isMultilingual: true,
  },
  {
    name: "descriptionShort",
    label: "_Description Short",
    placeholder: "",
    tooltipText: "_Description Short",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "text",
    aiEnable: true,
    isMultilingual: true,
  },
  {
    name: "description",
    label: "_Description",
    placeholder: "",
    tooltipText: "_Description",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "textarea",
    aiEnable: true,
    isMultilingual: true,
  },
  {
    name: "externalSources",
    label: "_External sources",
    placeholder: "",
    tooltipText: "External sources",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "externalSources",
    aiEnable: false,
    isMultilingual: false,
  },
  {
    multimedia: [
      {
        name: "primary[0]",
        bottomLabel: "primary Image",
        placeholder: "",
        tooltipText: "",
        tabName: "Media_tab",
        section: "Product profile Images",
        sectionTooltipText: "Product Profile Images",
        readOnly: false,
        type: "mediaImage",
      },
      {
        name: "frontal[0]",
        bottomLabel: "frontal Image",
        placeholder: "",
        tooltipText: "",
        tabName: "Media_tab",
        section: "Product profile Images",
        readOnly: false,
        type: "mediaImage",
      },
      {
        name: "backside[0]",
        bottomLabel: "backside Image",
        placeholder: "",
        tooltipText: "",
        tabName: "Media_tab",
        section: "Product profile Images",
        readOnly: false,
        type: "mediaImage",
      },
      {
        name: "square[0]",
        bottomLabel: "square Image",
        placeholder: "",
        tabName: "Media_tab",
        section: "Product profile Images",
        readOnly: false,
        tooltipText: "",
        type: "mediaImage",
      },
      {
        name: "logo[0]",
        bottomLabel: "logo Image",
        placeholder: "",
        tabName: "Media_tab",
        section: "Product profile Images",
        readOnly: false,
        tooltipText: "",
        type: "mediaImage",
      },
      {
        name: "other",
        label: "",
        placeholder: "",
        tooltipText: "",
        tabName: "Media_tab",
        section: "Other Images",
        sectionTooltipText: "Other Images",
        readOnly: false,
        type: "mediaImageOther",
      },
      {
        name: "other",
        label: "",
        placeholder: "",
        tabName: "Media_tab",
        section: "3D Models",
        sectionTooltipText: "3d Models",
        readOnly: false,
        tooltipText: "",
        type: "media3dmodel",
      },
      {
        name: "other",
        label: "",
        placeholder: "",
        tabName: "Media_tab",
        section: "Video",
        sectionTooltipText: "Videos",
        readOnly: false,
        tooltipText: "",
        type: "video",
      },
      {
        name: "pdf",
        label: "",
        placeholder: "",
        tabName: "Media_tab",
        section: "PDF file",
        readOnly: false,
        tooltipText: "",
        type: "pdf",
      },
      {
        name: "other",
        label: "",
        placeholder: "",
        tabName: "Media_tab",
        section: "Other file",
        sectionTooltipText: "Other Files",
        readOnly: false,
        tooltipText: "",
        type: "mediaOtherFile",
      },
    ],
  },
  {
    name: "videos",
    label: "",
    placeholder: "",
    tabName: "Media_tab",
    tooltipText: "",
    section: "Video URL",
    readOnly: false,
    type: "videoUrl",
  },
  {
    marketing: [
      {
        name: "websiteUrl",
        label: "_Website Url",
        placeholder: "Website Url",
        tooltipText: "Website Url",
        tabName: "Marketing_tab",
        readOnly: false,
        type: "text",
        isMultilingual: false,
      },
      {
        name: "overlayUrl",
        label: "_Overlay Url",
        placeholder: "",
        tooltipText: "Overlay Url",
        tabName: "Marketing_tab",
        readOnly: false,
        type: "text",
        isMultilingual: false,
      },
      {
        name: "publicEmail",
        label: "_Public Email",
        placeholder: "",
        tooltipText: "Public Email",
        tabName: "Marketing_tab",
        readOnly: false,
        type: "text",
        isMultilingual: false,
      },
      {
        name: "publicTelephone",
        label: "_Public Telephone",
        placeholder: "",
        tooltipText: "Public Telephone",
        tabName: "Marketing_tab",
        readOnly: false,
        type: "text",
        isMultilingual: false,
      },
      {
        name: "postalAddress[0]",
        subsection: "Postal Address",
        subSectionTooltipText: "Postal Address",
        tabName: "Marketing_tab",
        placeholder: "Line 1",
        readOnly: false,
        type: "text",
        isMultilingual: false,
      },
      {
        name: "postalAddress[1]",
        subsection: "Postal Address",
        tabName: "Marketing_tab",
        placeholder: "Line 2",
        readOnly: false,
        type: "text",
        isMultilingual: false,
      },
      {
        name: "postalAddress[2]",
        subsection: "Postal Address",
        tabName: "Marketing_tab",
        placeholder: "Line 3",
        readOnly: false,
        type: "text",
        isMultilingual: false,
      },
      {
        name: "postalAddress[3]",
        subsection: "Postal Address",
        tabName: "Marketing_tab",
        placeholder: "Line 4",
        readOnly: false,
        type: "text",
        isMultilingual: false,
      },

      {
        name: "marketingTexts",
        label: "_Marketing Texts",
        placeholder: "",
        tooltipText: "Marketing Text",
        tabName: "Marketing_tab",
        readOnly: false,
        type: "textarea",
        aiEnable: true,
        isMultilingual: true,
      },
      {
        name: "banner1",
        label: "_Top Banner",
        placeholder: "",
        tooltipText: "Top banner",
        tabName: "Marketing_tab",
        readOnly: false,
        type: "text",
        isMultilingual: true,
      },
      {
        name: "banner2",
        label: "_Lower Banner",
        placeholder: "",
        tooltipText: "Lower banner",
        tabName: "Marketing_tab",
        readOnly: false,
        type: "text",
        isMultilingual: true,
      },
      {
        name: "usageInstructions",
        label: "_Usage Instructions",
        placeholder: "",
        tooltipText: "Usage Instructions text",
        tabName: "Marketing_tab",
        readOnly: false,
        type: "textarea",
        isMultilingual: true,
      },
      {
        name: "buyNowUrls",
        label: "_Buy Now Urls",
        placeholder: "",
        tooltipText: "Buy now urls text",
        tabName: "Marketing_tab",
        readOnly: false,
        type: "urlMultiAdd",
        isMultilingual: false,
      },
      {
        name: "socialMediaUrls",
        label: "_Social Media Urls",
        placeholder: "",
        tooltipText: "Social media urls text",
        tabName: "Marketing_tab",
        readOnly: false,
        type: "urlMultiAdd",
        isMultilingual: false,
      },
      {
        name: "externalLinks",
        label: "_External Links",
        placeholder: "",
        tooltipText: "External links urls text",
        tabName: "Marketing_tab",
        readOnly: false,
        type: "urlMultiAdd",
        isMultilingual: false,
      },
    ],
  },
  {
    name: "certifications",
    label: "_Certifications",
    placeholder: "",
    tooltipText: "Select certifications",
    tabName: "Marketing_tab",
    readOnly: false,
    type: "certificationMultiSelectWithModal",
    // options: [
    //   { label: "UTZ", value: "utz" },
    //   { label: "Rainforest Alliance", value: "rainforestalliance" },
    // ],
    isMultilingual: false,
  },
  {
    carbonFootprint: [
      {
        name: "total",
        label: "Carbon footprint total",
        placeholder: "",
        tabName: "Marketing_tab",
        tooltipText: "_Carbon footprint total",
        section: "Carbon footprint",
        readOnly: false,
        type: "text",
        validation: "",
        isMultilingual: false,
      },
      {
        name: "dateOfCalculation",
        label: "Carbon footprint date of calculation",
        placeholder: "",
        tabName: "Marketing_tab",
        tooltipText: "_Carbon footprint date of calculation",
        section: "Carbon footprint",
        readOnly: false,
        type: "text",
        validation: "",
        isMultilingual: false,
      },
      {
        name: "source",
        label: "Carbon footprint source",
        placeholder: "",
        tabName: "Marketing_tab",
        tooltipText: "_Carbon footprint source",
        section: "Carbon footprint",
        readOnly: false,
        type: "text",
        validation: "",
        isMultilingual: false,
      },
      {
        name: "externalReference",
        label: "Carbon footprint external reference",
        placeholder: "",
        tabName: "Marketing_tab",
        tooltipText: "_Carbon footprint external reference",
        section: "Carbon footprint",
        readOnly: false,
        type: "text",
        validation: "",
        isMultilingual: false,
      },
    ],
  },
  {
    "marketing.custom": [
      {
        name: "bgColor",
        label: "_Background Color",
        placeholder: "",
        tabName: "Marketing_tab",
        tooltipText: "_Background Color",
        section: "Custom header",
        readOnly: false,
        type: "color",
        isMultilingual: false,
      },
      {
        name: "headerText",
        label: "_Header Text",
        placeholder: "",
        tabName: "Marketing_tab",
        tooltipText: "_Header Text",
        section: "Custom header",
        readOnly: false,
        type: "text",
        isMultilingual: false,
      },
    ],
  },
  {
    name: "emailConsent",
    label: "_Email consent",
    placeholder: "",
    tooltipText: "_Email consent",
    tabName: "Marketing_tab",
    readOnly: false,
    type: "emailConsent",
    isMultilingual: false,
  },
  {
    name: "restrictions",
    label: "_Restrictions",
    placeholder: "",
    tooltipText: "Restrictions",
    tabName: "Category_tab",
    readOnly: false,
    type: "restrictions",
    isMultilingual: false,
  },
  {
    category: [
      {
        name: "segmentCode.id",
        label: "_Segment",
        placeholder: "",
        tooltipText: "Select Segment",
        tabName: "Category_tab",
        readOnly: false,
        type: "select",
        isMultilingual: true,
      },
      {
        name: "familyCode.id",
        label: "_Family",
        dependsOnName: "segmentCode.id",
        placeholder: "",
        tooltipText: "Select family",
        tabName: "Category_tab",
        readOnly: false,
        type: "select",
        isMultilingual: true,
      },
      {
        name: "classCode.id",
        label: "_Class",
        dependsOnName: "familyCode.id",
        placeholder: "",
        tooltipText: "Select Class",
        tabName: "Category_tab",
        readOnly: false,
        type: "select",
        isMultilingual: true,
      },
      {
        name: "categoryCode.id",
        label: "_Category",
        dependsOnName: "classCode.id",
        placeholder: "",
        tooltipText: "Select Category",
        tabName: "Category_tab",
        readOnly: false,
        type: "select",
        isMultilingual: true,
      },
    ],
  },
  {
    name: "Technology",
    label: "_Technology",
    placeholder: "",
    tooltipText: "Technology",
    tabName: "Technology_tab",
    readOnly: false,
    type: "text",
    isMultilingual: false,
  },
  {
    name: "Versioning",
    label: "_Versioning",
    placeholder: "",
    tooltipText: "Versioning",
    tabName: "Versioning_tab",
    readOnly: false,
    type: "versioning",
    isMultilingual: false,
  },
  {
    name: "gs1DigitalLinkStructure",
    label: "",
    placeholder: "",
    tooltipText: "",
    type: "gs1DigitalLinkStructure",
    readOnly: true,
    value: {
      urlStructureList: [
        {
          value: '01/',
          label: ""

        },
        {
          name: 'gtin',
          label: "gtin"
        },
        {
          value: '/21/',
          label: ""
        },
        {
          name: 'upidsCodeSegment2',
          label: "upidsCodeSegment2"

        },
        {
          value: 'A',
          label: ""
        },
        {
          name: 'upidsCodeSegment3',
          label: "upidsCodeSegment3"
        }
      ],
    }
  }
];
